### ISSUE TITLE
글쓴이 검색 추가

### ISSUE THREAD

**Issue by mirusu400** [pgh268400/DCINSIDE_SEARCH#1]
https://github.com/pgh268400/DCINSIDE_SEARCH/blob/5ef16328dffbc955dc2e3801e44bfdf4729313ec/no_gui.py#L73-L77

지금은 글내용으로밖에 검색 안되는데 글 작성자로 검색기능이나 제목/댓글 검색기능도 추가하면 좋을거 같습니다

**Comment by pgh268400** [comment]
안녕하세요? 보내주신 피드백 확인했습니다 사실 만들어야 하는 기능인데 귀찮아서 빨리 만들고 건들질 않았네요 ㅎㅎ..

혹시 클라스 헬퍼에 제작하신분인가요?? 혹시 맞다면 정말 잘사용하고 있습니다 ~
우연으로 들어오신진 모르겠지만 저도 광운대 동문이거든요..
군대 얘기 나온거보니 선배님이신듯 한데 여기서 뵙다니 정말 신기하네요 ㅎㅎ;;

**Comment by pgh268400** [comment]
아 저는 21학번입니다 ㅋㅋ 사실 그냥 필요해서 5일간 빡세게 만들어서 다른 컴퓨터에서 실행 여부는 확인을 못해봤네요
그리고 main.py가 실행 안되는 이유는 당연한데
main.py가 완전히 다른 파일이 들어가 있었네요..? ㅋㅋㅋㅋ
 그냥 다시 올려야 할 거 같습니다

암튼 피드백 감사드려요~ 좀 정리해보겠습니다 ^^
